export enum AdminAuditAction {
  LOGIN_SUCCESS = 'login_success',
  LOGIN_FAILED = 'login_failed',
  LOGOUT = 'logout',
  LOCK_USER = 'lock_user',
  UNLOCK_USER = 'unlock_user',
  ADMIN_DEPOSIT = 'admin_deposit',
  ADMIN_WITHDRAW = 'admin_withdraw',
  CREATE_USER = 'create_user',
  APPROVE_TRANSACTION = 'approve_transaction',
  REJECT_TRANSACTION = 'reject_transaction',
  FREEZE_ACCOUNT = 'freeze_account',
  UNFREEZE_ACCOUNT = 'unfreeze_account',
  UPDATE_SETTINGS = 'update_settings',
  DELETE_USER = 'delete_user',
}
